CREATE TABLE IF NOT EXISTS SLIDER (
    SLIDER_ID INTEGER PRIMARY KEY,
    SLIDER_VALUE INTEGER NOT NULL,
    START_TIME INTEGER,
    END_TIME INTEGER
);

INSERT INTO SLIDER VALUES(1, 0, 0, NULL);
INSERT INTO SLIDER VALUES(2, 0, 0, NULL);
INSERT INTO SLIDER VALUES(3, 0, 0, NULL);
INSERT INTO SLIDER VALUES(4, 0, 0, NULL);
INSERT INTO SLIDER VALUES(5, 0, 0, NULL);
